name: garnet
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  # -- Runtime dependencies
  # base: list all base dependencies here
  - python>=3.8  # please specify the mimimum version of python here
  - versioningit
  # compute: list all compute dependencies here
  - numpy
  - pandas
  # plot: list all plot dependencies here, if applicable
  - matplotlib
  # jupyter: list all jupyter dependencies here, if applicable
  - jupyterlab
  - ipympl
  # -- Development dependencies
  # utils:
  - pre-commit
  # pacakge building:
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  # test: list all test dependencies here
  - pytest
  - pytest-qt
  - pytest-cov
  - pytest-xdist
  # --------------------------------------------------
  # add additional sections such as Qt, etc. if needed
  - boa
  - mantidworkbench 
  - check-wheel-contents
  - pylint=2.17.3
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - pyoncat
  - gtk3
  - libstdcxx-ng
  # --------------------------------------------------
  # if pakcages are not available on conda, list them here
  - pip
  - pip:
    - bm3d-streak-removal # example
    - pytest-playwright
