name: garnet-developer
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
dependencies:
  - anaconda-client
  - boa
  - check-wheel-contents
  - conda-build
  - conda-verify
  - mantidworkbench
  - pre-commit
  - python-build
  - pyoncat
  - pytest
  - pytest-qt
  - pytest-cov
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - sphinxcontrib-mermaid
  - versioningit
