name: garnet
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
  - defaults
dependencies:
  # base
  - python=3.10
  - setuptools
  # runtime
  - mantidworkbench
  - numpy
  - pandas
  # plot
  - matplotlib
  # jupyter
  - jupyterlab
  - ipympl
  # -- Dev dependencies
  # utils
  - pre-commit
  # packaging
  - check-wheel-contents
  - boa
  - conda-build
  - conda-verify
  - python-build
  - versioningit
  - libmambapy=1.4.2  # auto-selected libarchive=3.6.2 depends on this version
  # test
  - pytest
  - pytest-qt
  - pytest-cov
  - pytest-xdist
  - pytest-runner
  # --------------------------------------------------
  # add additional sections such as Qt, etc. if needed
  - sphinx
  - sphinx-rtd-theme
  - pyoncat
  - gtk3
  - libstdcxx-ng
  # --------------------------------------------------
  # if pakcages are not available on conda, list them here
