name: garnet
channels:
  - conda-forge
  - mantid/label/nightly
  - oncat
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - mantidworkbench
  - pre-commit
  - check-wheel-contents
  - boa
  - conda-build
  - conda-verify
  - python-build
  - versioningit
  - libmambapy=1.4.2  # auto-selected libarchive=3.6.2 depends on this version
  - pytest
  - pytest-qt
  - pytest-cov
  - sphinx
  - sphinx-rtd-theme
  - pyoncat
  - gtk3
  - libstdcxx-ng
